apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 5m
  chart:
    spec:
      version: "1.9.9"
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana-tempo
      interval: 60m
  # https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml
  values:
