apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  selector: {}
  podMetricsEndpoints: []
