apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emojivote
  namespace: emojivote
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/applications/base
resources:
- ns.yml
- web.yml
- emoji.yml
- voting.yml
- vote-bot.yml
