apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-agent
spec:
  interval: 5m
  chart:
    spec:
      version: "0.38.0"
      chart: grafana-agent
      sourceRef:
        kind: HelmRepository
        name: grafana-agent
      interval: 60m
  # https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/values.yaml
  values:
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi